home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('addKegiatan/', views.addKegiatan, name='addKegiatan'),
    path("addMahasiswa/<int:id>",views.addMahasiswa,name="addMahasiswa"),
    path("mahasiswa/<str:nama>",views.detailMahasiswa,name="detailMahasiswa"),
    path("kegiatan/<str:nama>",views.detailKegiatan,name="detailKegiatan"),

]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('search/', views.search, name='search'),
]

story9/urls.py
from django.urls import path, include

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

   
]

story_ext/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

home/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models
from django.shortcuts import reverse


class Mahasiswa(models.Model):
    nama = models.TextField(max_length=100, unique=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        link = self.nama.replace(" ","-")
        return reverse("story6:detailMahasiswa",args=[link])

class Kegiatan(models.Model):
    nama = models.TextField(max_length=100,unique=True)
    mahasiswa = models.ManyToManyField(Mahasiswa,blank=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        link = self.nama.replace(" ","-")
        return reverse("story6:detailKegiatan",args=[link])

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import Kegiatan, Mahasiswa

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        exclude = ["mahasiswa"]

class MahasiswaForm(forms.ModelForm):
    class Meta:
        model = Mahasiswa
        fields = "__all__"

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, initial='Anon')
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

home/views.py
from django.shortcuts import render



def homepage(request):
    return render(request, 'home.html')

story6/views.py
from django.shortcuts import get_object_or_404, redirect, render, reverse
from .models import Mahasiswa, Kegiatan
from .forms import MahasiswaForm, KegiatanForm


def homepage(request):
    context = {
        "kegiatanList" : Kegiatan.objects.all(),
    }
    return render(request, 'homepage.html', context)

def addKegiatan(request):
    if (request.method == "POST"):
        kegiatanForm = KegiatanForm(request.POST)
        if (kegiatanForm.is_valid()):
            kegiatanForm.save()
        return redirect("story6:homepage")
    return render(request,"addKegiatan.html")

def detailKegiatan(request, nama):
    nama = nama.replace("-"," ")
    kegiatan = get_object_or_404(Kegiatan,nama=nama)
    context = {
        "kegiatan" : kegiatan,
    }
    return render(request,"detailKegiatan.html",context)


def addMahasiswa(request, id):
    if (request.method == "POST"):
        kegiatan = Kegiatan.objects.get(id=id)
        namaMahasiswa = request.POST["nama"]

        mahasiswaBaru, isCreate = Mahasiswa.objects.get_or_create(nama=namaMahasiswa)
        if (isCreate):
            mahasiswaBaru.save()
            kegiatan.mahasiswa.add(mahasiswaBaru) # Membuat dan menambah objek mahasiswa baru
        else:
            try:
                kegiatan.mahasiswa.get(nama=namaMahasiswa) # Jangan add peserta yang sudah di kegiatan.
            except:
                kegiatan.mahasiswa.add(mahasiswaBaru) # Add peserta baru yang ada di database tapi tidak di kegiatan.
    return redirect(reverse("story6:detailKegiatan",args=[kegiatan.nama.replace(" ","-")]))

def detailMahasiswa(request,nama):
    nama = nama.replace("-"," ")
    mahasiswa = get_object_or_404(Mahasiswa,nama=nama)
    context = {
        "mahasiswa" : mahasiswa
    }
    return render(request,"detailMahasiswa.html",context)

story7/views.py
from django.shortcuts import render



def homepage(request):
    return render(request, 'story7/homepage.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json


def homepage(request):
    return render(request, 'story8/homepage.html')

def search(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    jsonData = json.loads(requests.get(url).content)
    return JsonResponse(jsonData, safe=False)

story9/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as django_logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import SignUpForm

# Create your views here.
def homepage(request):
    return render(request, 'story9/homepage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('story9:homepage')
    else:
        form = SignUpForm()
    return render(request, 'story9/signup_views.html', {'form': form})

home/templates/home.html
{% load static %}
<html>
    <head>
        <title>Homepage</title>
    </head>
    <body>
        <h1>
            List Story
        </h1>
        <ul>
            <li><a href="{% url 'story6:homepage' %}">Story 6</a></li>
            <li><a href="{% url 'story7:homepage' %}">Story 7</a></li>
            <li><a href="{% url 'story8:homepage' %}">Story 8</a></li>
            <li><a href="{% url 'story9:homepage' %}">Story 9</a></li>
        </ul>
    </body>
</html>

story6/templates/addKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="title">
    <h3>Daftar Kegiatan Baru</h3>
</div>

    <div class="column">
        <div class="form-group">
            <form method="POST" action="{% url 'story6:addKegiatan' %}">
                {% csrf_token %}
                <div>
                    <label>Nama Kegiatan</label>
                    <input placeholder="Nama" class="form-control" name="nama" required>
                </div>
                <br>
                <button type="submit" class="btn btn-dark">Confirm</button>
            </form>
        </div>
    </div>


    


{% endblock content %}

story6/templates/base.html
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <title>MyActivities</title>
    </head>
    <body>
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'story6:homepage' %}">MyActivities</a>
                </div>
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'story6:addKegiatan' %}">Tambah Kegiatan</a></li>
                </ul>
              </div>
        </div>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        </div>

    </body>
</html>

story6/templates/detailKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="title">
        <h3>
            {{ kegiatan.nama }}
        </h3>
    </div>
    <div class="column">
        <p>Peserta: </p>
        <ol>
            {% for mahasiswa in kegiatan.mahasiswa.all %}
            <li>
                <a href="{{ mahasiswa.get_absolute_url }}">
                    {{ mahasiswa.nama }}
                </a>
               
            </li>
            {% endfor %}
        </ol>
        <div class="form-group">
            <form method="POST" action="{% url 'story6:addMahasiswa' id=kegiatan.id %}">
                {% csrf_token %}
                <div>
                    <label>Tambah Mahasiswa</label>
                    <input placeholder="Nama" class="form-control" name="nama" required>
                </div>
                <br>
                <button type="submit" class="btn btn-dark">Confirm</button>
            </form>
        </div>

    </div>
{% endblock content %}

story6/templates/detailMahasiswa.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="title">
    <h3>Detail Kegiatan {{ mahasiswa.nama }}</h3>
</div>
<div class="column">
    <ol>
        {% for kegiatan in mahasiswa.kegiatan_set.all %}
        <li>
            <a href="{{ kegiatan.get_absolute_url }}">
                {{ kegiatan.nama }}
            </a>
        </li>
        {% endfor %}
    </ol>
</div>

{% endblock content %}

story6/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="title">
    <h3>
        Daftar Kegiatan
    </h3>
</div>
<div class="wrap">
    {% for kegiatan in kegiatanList %}
    <div class="kegiatan-block">
        <div class="list-kegiatan">
            <div class="title">
                <a href="{{kegiatan.get_absolute_url}}">
                    {{ kegiatan.nama }}
                </a>
            </div>
            <p>Peserta: </p>
            <ol>
                {% for mahasiswa in kegiatan.mahasiswa.all %}
                <li>
                    {{ mahasiswa.nama }}
                </li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

story7/templates/story7/homepage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Story 7</title>

    <!--CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'story7/css/styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    

    <!-- JQuery -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'story7/js/script.js' %}"></script>

  </head>
  <body>
    <h1 class="text-center">Story 7</h1>
    <h4 class="text-center">
      Membuat accordion menggunakan JavaScript dan JQuery
    </h3>
    <div id="accordion">
      <h3 class="sub" position="0">Aktivitas saat ini
        <button type="button" style="float: right;" class="btn btn-primary up">
          Up
        </button>
        <button type="button" style="float: right" class="btn btn-primary down">
          Down
        </button>
    </h3>
      <div position="0">
        <p>
        Kegiatan yang sering saya lakukan saat ini adalah mengerjakan tugas. 
        Juga diselingi bermain game saat istirahat atau saat tidak ada tugas.
        </p>
      </div>

      <h3 class="sub" position="1">Pengalaman organisasi/kepanitiaan
        <button type="button" style="float: right;" class="btn btn-primary up">
          Up
          </button>
          <button type="button" style="float: right" class="btn btn-primary down">
            Down
          </button>
      </h3>
      <div position="1">
        <p>
          Berikut adalah pengalaman organisasi dan kepanitiaan
        </p>
        <ul>
          <li>Pengajar Betis</li>
          <li>Koor mentor DDP 1,5</li>
          <li>Asdos matdis 1</li>
        </ul>
      </div>

      <h3 class="sub" position="2">Prestasi
          <button type="button" style="float: right;" class="btn btn-primary up">
            Up
          </button>
          <button type="button" style="float: right" class="btn btn-primary down">
            Down
          </button>
      </h3>
      <div position="2">
        <p>
          Berikut adalah penghargaan yang pernah saya capai dalam hidup ini
        </p>
        <ul>
          <li>Mengikuti OSK bidang Kimia</li>
          <li>Pernah menjadi top 10 lokal hero Kagura di ML</li>
          <li>Berhasil masuk Fasilkom UI</li>
          <li>Memiliki gacha yang ampas</li>
        </ul>
      </div>

      <h3 class="sub" position="3">Alasan masuk ke Fasilkom UI
        <button type="button" style="float: right;" class="btn btn-primary up">
          Up
        </button>
        <button type="button" style="float: right" class="btn btn-primary down">
          Down
        </button>
      </h3>
      <div position="3">
        <p>
        Karena saya suka bermain game, saya jadi memiliki keinginan untuk membuat game sendiri.
        Sehingga saya memilih untuk masuk ke jurusan yang berhubungan dengan komputer. Awalnya mengikuti
        SNMPTN dan memilih Teknik Komputer dan untungnya gagal. Karena dulu saya tidak mengetahui bahwa yang melakukan
        programming adalah Ilmu Komputer. Sehingga saya mengikuti SBMPTN dan mendaftar Ilmu Komputer. Lalu saya diterima
        dan masuk ke Fasilom UI.
        </p>
      </div>
    </div>

    <div>
      <a style="margin: 10px;" href="https://pepewe-story.herokuapp.com/story3/">Profil Utama</a>
    </div>
    
    
  
  </body>
</html>

story8/templates/story8/homepage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Story 8</title>

    <!--CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'story8/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    

    <!-- JQuery -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'story8/js/script.js' %}"></script>

  </head>
  <body>
    <h1 class="text-center">
      Books Searcher
    </h1>
    <form id = "form" class="text-center">
      <input type="search" class="" id="search" placeholder="Book Name">
    </form>
    <ol id="items-list" class="items-list"> 

    </ol>
  
    
    
  
  </body>
</html>

story9/templates/story9/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Story 9</title>

    <!--CSS-->
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    


    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

story9/templates/story9/homepage.html
{% extends "story9/base.html" %}
{% load static %}

{% block content %}
    <nav class="navbar navbar-dark bg-primary d-block">
      <a class="navbar-brand" style="font-size: 30px;" href="#">Story 9</a>
      <div class="navbar-default navbar-dark bg-primary float-right" id="navbarText">

        <span class="navbar-text">
          {% if user.is_authenticated %}
            <span style="font-size: 16px; color: white;" class="mr-5">Halo, {{ user.username }}</span>
            
            <a href="/story9/accounts/logout/?next=/story9">Logout</a>
          {% else %}
            <a href="/story9/accounts/login/?next=/story9" class="mr-5">Login</a>
            <a href="{% url 'story9:signup' %}">Signup</a>
          {% endif %}
          
        </span>
      </div>
    </nav>

    <div class="mx-5">
      {% if user.is_authenticated %}
      <h2>Selamat Datang {{ user.first_name }}</h2> 
      <video width='320' height= '240' controls>
        <source src="{% static 'story9/some_video.mp4'%}" type='video/mp4'>
        </video>
        
      {% else %}
        <h2>Silahkan login terlebih dahulu untuk melihat konten.</h2>
      {% endif %}
      </div>

    
{% endblock %}

story9/templates/story9/signup_views.html
{% extends "story9/base.html" %}
{% load static %}

{% block content %}
<div class="text-center">
    <h2>Sign up</h2>
    <form method="post" class="mt-5">
    {% csrf_token %}
    <p>
        {{ form.username.label_tag }} {{ form.username }} <br>
        <small style="color: grey">Hanya bisa huruf, angka, dan @/./+/-/_ saja</small>
        {% for error in form.username.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>
    <p>
        {{ form.first_name.label_tag }} {{ form.first_name }} <br>
        <small style="color: grey">Wajib diisi.</small>
    </p>
    <p>
        {{ form.last_name.label_tag }} {{ form.last_name }} <br>
    </p>
    <p>
        {{ form.email.label_tag }} {{ form.email }} <br>
        <small style="color: grey">Gunakan format email yang benar.</small>
        {% for error in form.email.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>

    <p>
        {{ form.password1.label_tag }} {{ form.password1 }} <br>
        <small style="color: grey">Minimal 8 huruf dan tidak bisa semuanya angka.</small>
        {% for error in form.password1.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>

    <p>
        {{ form.password2.label_tag }} {{ form.password2 }} <br>
        <small style="color: grey">Ketik password yang sama untuk konfirmasi.</small>
        {% for error in form.password2.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>

        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
</div>

       
{% endblock %}